<!DOCTYPE html>
<html lang = "pt-br">

<head>
    <meta charset = "utf-8">
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css">
    <title>Error: 404</title>
</head>

<body>
    <input type="checkbox"  id="control-menu" />
                <label for="control-menu"    class="control-menu"></label>
                <label for="control-menu"    class="menu-icon" ><img src="https://cdn1.iconfinder.com/data/icons/feather-2/24/minus-square-128.png" width=45px style="top:0"></label>

    <nav class="menu" style="top:0">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/posts">Posts</a></li>
        </ul>
    </nav>

    <div class="container">
        <h1>Erro: 404</h1>
        <h2>Página não encontrada</h2>
        <p>Verifique se a URL está correta.</p>
</body>

</html>
