<input type="checkbox"  id="control-menu" />
            <label for="control-menu"    class="control-menu"></label>
            <label for="control-menu"    class="menu-icon"><img src="https://cdn1.iconfinder.com/data/icons/feather-2/24/minus-square-128.png" width=45px></label>

<nav class="menu">
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/posts">Posts</a></li>
    </ul>
</nav>
